// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCetKhHXX4o3tYupIA5RcuH9PKb-Npz2Fk',
    appId: '1:132713707345:web:19b2289d7612471a1fc570',
    messagingSenderId: '132713707345',
    projectId: 'finnsocial-48ed5',
    authDomain: 'finnsocial-48ed5.firebaseapp.com',
    storageBucket: 'finnsocial-48ed5.firebasestorage.app',
    measurementId: 'G-211NNPB1GS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKy91HjihXducwJkppV43IF9tLfqD-oHU',
    appId: '1:132713707345:android:31384461a1c55add1fc570',
    messagingSenderId: '132713707345',
    projectId: 'finnsocial-48ed5',
    storageBucket: 'finnsocial-48ed5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5Zb9BmUiM5Ly1DJtwFQ2D5_zz8RAge4U',
    appId: '1:132713707345:ios:5f3147150bc6ed1e1fc570',
    messagingSenderId: '132713707345',
    projectId: 'finnsocial-48ed5',
    storageBucket: 'finnsocial-48ed5.firebasestorage.app',
    iosBundleId: 'com.example.memeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5Zb9BmUiM5Ly1DJtwFQ2D5_zz8RAge4U',
    appId: '1:132713707345:ios:5f3147150bc6ed1e1fc570',
    messagingSenderId: '132713707345',
    projectId: 'finnsocial-48ed5',
    storageBucket: 'finnsocial-48ed5.firebasestorage.app',
    iosBundleId: 'com.example.memeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCetKhHXX4o3tYupIA5RcuH9PKb-Npz2Fk',
    appId: '1:132713707345:web:41ae0518f6ed03901fc570',
    messagingSenderId: '132713707345',
    projectId: 'finnsocial-48ed5',
    authDomain: 'finnsocial-48ed5.firebaseapp.com',
    storageBucket: 'finnsocial-48ed5.firebasestorage.app',
    measurementId: 'G-0B92NG6EDL',
  );

}